server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(mp4|webm|webp|js|css)$ {
    add_header Accept-Ranges bytes;
    add_header Cache-Control "public, max-age=604800";
    try_files $uri =404;
  }
}
